sources:
  - Assets/Models/
templates:
  - Assets/SourceryGenerated/Templates/AutoCodable.swifttemplate
  - Assets/SourceryGenerated/Templates/AutoEquatable.stencil
  - Assets/SourceryGenerated/Templates/AutoMockable.stencil
output:
  Assets/SourceryGenerated
