sources:
  - Asset/Models/
templates:
  - Asset/SourceryGenerated/Templates/AutoCodable.swifttemplate
  - Asset/SourceryGenerated/Templates/AutoEquatable.stencil
  - Asset/SourceryGenerated/Templates/AutoMockable.stencil
output:
  Asset/SourceryGenerated
