name: "BrightFutures"

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: macOS-latest
    env: 
      DEVELOPER_DIR: /Applications/Xcode_12.4.app/Contents/Developer

    steps:
      - uses: actions/checkout@v2
      - name: macOS
        run: xcodebuild test -project BrightFutures.xcodeproj -scheme BrightFutures-Mac
      - name: iOS
        run: xcodebuild test -project BrightFutures.xcodeproj -scheme BrightFutures-iOS -sdk iphonesimulator -destination "platform=iOS Simulator,OS=14.4,name=iPhone 12 mini"
      - name: tvOS
        run: xcodebuild test -project BrightFutures.xcodeproj -scheme BrightFutures-tvOS -sdk appletvsimulator -destination "OS=14.3,name=Apple TV 4K"
      - name: watchOS
        run: xcodebuild build -project BrightFutures.xcodeproj -scheme BrightFutures-watchOS -sdk watchsimulator